"""End-to-end builder + emit + validation tests."""

from __future__ import annotations

from collections.abc import Callable

import pytest

import ocsf_emitter
from ocsf_emitter import (
    Activity,
    Confidence,
    InvalidFindingError,
    MitreAttack,
    Observable,
    ObservableType,
    OcsfEmitterError,
    RiskLevel,
    Severity,
    Status,
    build_detection_finding,
    emit,
    validate,
)
from ocsf_emitter._models import DetectionFinding
from ocsf_emitter.defaults import CATEGORY_UID, CLASS_UID

from .conftest import FIXED_TIME_MS


def _build(clock: Callable[[], int]) -> DetectionFinding:
    return build_detection_finding(
        uid="det-123",
        title="Impossible-travel login",
        severity=Severity.HIGH,
        message="User logged in from two continents within minutes.",
        status=Status.NEW,
        activity=Activity.CREATE,
        observables=[
            Observable(ObservableType.USER_NAME, "alice"),
            Observable(ObservableType.IP_ADDRESS, "203.0.113.7"),
        ],
        description="Geo-velocity rule R-42 fired.",
        data_sources=["okta.system_log"],
        confidence=Confidence.HIGH,
        confidence_score=95,
        risk_level=RiskLevel.HIGH,
        risk_score=80,
        attacks=[MitreAttack("T1078", "Valid Accounts", "TA0001", "Initial Access")],
        count=1,
        time_ms=FIXED_TIME_MS,
        clock=clock,
    )


def test_valid_finding_round_trips(fixed_clock: Callable[[], int]) -> None:
    finding = _build(fixed_clock)
    payload = emit(finding)

    assert payload["class_uid"] == CLASS_UID
    assert payload["category_uid"] == CATEGORY_UID
    assert payload["class_name"] == "Detection Finding"
    assert payload["category_name"] == "Findings"
    assert payload["type_uid"] == 200401
    assert payload["severity_id"] == 4
    assert payload["status_id"] == 1
    assert payload["activity_id"] == 1
    assert payload["confidence_id"] == 3
    assert payload["risk_level_id"] == 3
    assert payload["time"] == FIXED_TIME_MS
    assert payload["metadata"]["version"] == ocsf_emitter.OCSF_SCHEMA_VERSION
    assert payload["finding_info"]["uid"] == "det-123"
    assert payload["finding_info"]["attacks"][0]["technique"]["uid"] == "T1078"
    assert {o["type_id"] for o in payload["observables"]} == {2, 4}


def test_emitted_payload_reparses_as_valid_ocsf(fixed_clock: Callable[[], int]) -> None:
    """The emitted dict must reconstruct a valid DetectionFinding (schema round-trip)."""
    payload = emit(_build(fixed_clock))
    reparsed = ocsf_emitter.models.DetectionFinding.model_validate(payload)
    # validate() should accept the reparsed model too.
    validate(reparsed)


def test_uid_autogenerated_when_omitted() -> None:
    calls: list[int] = []

    def uid_factory() -> str:
        calls.append(1)
        return "generated-uid"

    finding = build_detection_finding(
        title="t",
        severity=Severity.LOW,
        message="m",
        uid_factory=uid_factory,
    )
    assert finding.finding_info.uid == "generated-uid"
    assert calls == [1]


def test_missing_product_raises(monkeypatch: pytest.MonkeyPatch) -> None:
    # Clear the configured product for this test only.
    monkeypatch.setattr(ocsf_emitter.defaults, "_DEFAULT_PRODUCT", None)
    with pytest.raises(OcsfEmitterError, match="No product configured"):
        build_detection_finding(title="t", severity=Severity.LOW, message="m")


def test_per_call_product_override() -> None:
    product = ocsf_emitter.make_product(name="Override", vendor_name="V")
    finding = build_detection_finding(
        title="t", severity=Severity.LOW, message="m", product=product
    )
    payload = emit(finding)
    assert payload["metadata"]["product"]["name"] == "Override"


def test_invalid_finding_rejected(fixed_clock: Callable[[], int]) -> None:
    """Corrupting a required field must raise InvalidFindingError naming it."""
    finding = _build(fixed_clock)
    finding.severity_id = "not-a-valid-enum"  # type: ignore[assignment]  # deliberately corrupt
    with pytest.raises(InvalidFindingError) as excinfo:
        emit(finding)
    assert any("severity_id" in fe for fe in excinfo.value.field_errors)


def test_pinned_version_is_security_lake_compatible() -> None:
    """Guard the pin: AWS Security Lake / its OCSF validator accept only these."""
    assert ocsf_emitter.OCSF_SCHEMA_VERSION in {"1.1.0", "1.0.0-rc.2"}


def test_invalid_type_uid_rejected(fixed_clock: Callable[[], int]) -> None:
    """type_uid inconsistent with activity_id must be caught by invariant check."""
    finding = _build(fixed_clock)
    # Valid enum member, but wrong for activity CREATE (expects 200401).
    finding.type_uid = ocsf_emitter.models.TypeUid(200402)
    with pytest.raises(InvalidFindingError) as excinfo:
        validate(finding)
    assert any("type_uid" in fe for fe in excinfo.value.field_errors)
